pipeline {
    agent any

    environment {
        AWS_REGION = "us-east-1"

        FRONTEND_REPO = "975800361242.dkr.ecr.us-east-1.amazonaws.com/devops-capstone/frontend"
        BACKEND_REPO  = "975800361242.dkr.ecr.us-east-1.amazonaws.com/devops-capstone/backend"
    }

    stages {

        stage('Checkout Source') {
            steps {
                checkout scm
            }
        }

        stage('Generate Image Tag') {
            steps {
                script {
                    env.IMAGE_TAG = sh(
                        script: "git rev-parse --short HEAD",
                        returnStdout: true
                    ).trim()

                    echo "Image Tag: ${env.IMAGE_TAG}"
                }
            }
        }

        stage('Login to Amazon ECR') {
            steps {
                sh '''
                aws ecr get-login-password --region ${AWS_REGION} | \
                docker login \
                --username AWS \
                --password-stdin \
                975800361242.dkr.ecr.us-east-1.amazonaws.com
                '''
            }
        }

        stage('Build Frontend Image') {
            steps {
                sh '''
                docker build \
                -t $FRONTEND_REPO:$IMAGE_TAG \
                -f app-repo/frontend/Dockerfile \
                app-repo/frontend
                '''
            }
        }

        stage('Build Backend Image') {
            steps {
                sh '''
                docker build \
                -t ${BACKEND_REPO}:$IMAGE_TAG \
                -f app-repo/backend/Dockerfile \
                app-repo/backend
                '''
            }
        }

    


stage('Push Frontend Image') {
    steps {
        sh '''
        docker push $FRONTEND_REPO:$IMAGE_TAG
        '''
    }
}

stage('Push Backend Image') {
    steps {
        sh '''
        docker push $BACKEND_REPO:$IMAGE_TAG
        '''
      }
    }
  
stage('Deploy to Kubernetes') {
    steps {
        sh """
        helm upgrade --install capstone-app \
        app-repo/helm/capstone-app \
        -n dev \
        -f app-repo/helm/capstone-app/values-dev.yaml \
        --set frontend.image.repository=${FRONTEND_REPO} \
        --set backend.image.repository=${BACKEND_REPO} \
        --set frontend.image.tag=${IMAGE_TAG} \
        --set backend.image.tag=${IMAGE_TAG}
        """
    }
}
stage('Wait for Rollout') {
    steps {
        sh '''
        kubectl rollout status deployment/frontend -n dev --timeout=5m
        kubectl rollout status deployment/backend -n dev --timeout=5m
        '''
    }
}

stage('Verify Pods') {
    steps {
        sh '''
        kubectl get pods -n dev -o wide
        '''
    }
}

stage('Verify Ingress') {
    steps {
        sh '''
        kubectl get ingress -n dev
        '''
    }
}

stage('Smoke Test') {
    steps {
        sh '''
        ALB=$(kubectl get ingress capstone-app-ingress -n dev -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')

        curl -f http://$ALB

        curl -f http://$ALB/health

        curl -f http://$ALB/api/health
        '''
    }
}




   } 

}
  
