namespace: dev

frontend:
  replicaCount: 1
  image:
    tag: 46b06c8
  env:
    appEnv: DEV
    apiBaseUrl: ""

backend:
  replicaCount: 1
  image:
    tag: 46b06c8
  env:
    appEnv: dev
    appVersion: "1.0.0-dev"

ingress:
  enabled: true
  className: alb
  host: ""
