apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-runtime-config
  namespace: {{ .Values.namespace }}
data:
  config.js: |
    window.RUNTIME_CONFIG = {
      APP_ENV: "{{ .Values.frontend.env.appEnv }}",
      API_BASE_URL: "{{ .Values.frontend.env.apiBaseUrl }}"
    };
